[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@9.15.4 --activate",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm build --filter=admin"]

[start]
cmd = "cd apps/admin && pnpm start -p $PORT"
