[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@9.15.4 --activate",
  "pnpm install --frozen-lockfile --no-optional"
]

[phases.build]
cmds = [
  "pnpm turbo build --filter=web",
  "pnpm turbo build --filter=merchant",
  "pnpm turbo build --filter=customer",
  "pnpm turbo build --filter=pos",
  "pnpm turbo build --filter=admin"
]

[start]
cmd = "pm2-runtime start ecosystem.config.js"
