[phases.setup]
nixPkgs = ["nodejs_22", "pnpm-9_x"]

[phases.install]
cmds = [
  "npm install -g corepack@0.24.1 && corepack enable",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm build --filter=admin"]

[start]
cmd = "cd apps/admin && pnpm start"
